### ISSUE TITLE
Update latest GCC ARM toolchain

### ISSUE THREAD

**Issue by vanbwodonk** [PaulStoffregen/ARM_Toolchain_2014q1_Source#2]
Hi Paul, Any chance to update into latest GCC-Arm-Embedded build? Or ARM teensy Always used 2014q1 compiler?

**Comment by PaulStoffregen** [comment]
Please ask on the forum, not here.  This issue tracker is only for reporting specific problems.

https://forum.pjrc.com/forums/4-Suggestions-amp-Bug-Reports
